### ISSUE TITLE
TODO: Test suite

### ISSUE THREAD

**Issue by sebnarvaez** [larvasapiens/htm-teul#1]
A test suite that receives:
- [x] The data for training
- [x] The data for testing
- [x] The structure
- [x] The modules

Outputs a report with the inputs plus:
- [x] Which data was succesfully predicted, and which wasn't
